import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const source=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
let waiting=[],calls=[];
const context={Promise,stockPeriod:'THIS_MONTH',stockPeriodEpoch:0,live:{stockPnl:null},render(){},kstDate:()=> '2026-01-05',rpcDirect(name,payload){calls.push([name,payload]);return new Promise((resolve,reject)=>waiting.push({resolve,reject}))}};
vm.createContext(context);
vm.runInContext(source.slice(source.indexOf('  var stockCalculationTail='),source.indexOf('  function rpcDirect(')),context);
vm.runInContext(source.slice(source.indexOf('  function changeStockPeriod('),source.indexOf('  function stockPeriodPerformance(')),context);
const flush=()=>new Promise(resolve=>setImmediate(resolve));
const first=context.changeStockPeriod('THIS_MONTH');await flush();
context.changeStockPeriod('THIS_MONTH');assert.equal(calls.length,1,'double taps do not duplicate work');
const second=context.changeStockPeriod('ALL');await flush();assert.equal(calls.length,1,'heavy requests run sequentially');
waiting.shift().resolve({ok:true,period:'THIS_MONTH'});await first;await flush();assert.equal(context.live.stockPnl,null,'stale period cannot overwrite current period');
assert.equal(calls.length,2);waiting.shift().reject(new Error('timeout'));await second;
assert.equal(context.live.stockPnlLoading,false);assert.equal(context.live.stockPnlFailed,true);
const retry=context.changeStockPeriod('ALL');await flush();waiting.shift().resolve({ok:true,period:'ALL',items:[]});await retry;
assert.equal(context.live.stockPnl.period,'ALL');assert.equal(context.live.stockPnlFailed,false,'manual retry recovers without full refresh');
const today=context.changeStockPeriod('오늘');await flush();waiting.shift().resolve({ok:true,period:'오늘',period_start:'2026-01-04',period_end:'2026-01-04'});await today;
assert.equal(context.live.stockPnl,null,'yesterday data cannot appear as today');
const swapped=context.changeStockPeriod('THIS_MONTH');await flush();const replacement={stockPnl:null};context.live=replacement;waiting.shift().resolve({ok:true,period:'THIS_MONTH'});await swapped;assert.equal(replacement.stockPnl,null,'replaced account snapshot is not overwritten');
assert.match(source,/id="stockPnlRetry"/);console.log('Build131 recovery, queue, duplicate, stale-period/day/snapshot checks passed');
