import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import {test} from 'node:test';
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
const section=(a,b)=>html.slice(html.indexOf(a),html.indexOf(b,html.indexOf(a)));
const code=section('  function decisionDraftKey(', '  function readDecisionDraft(')+section('  var homeSnapshotPreview=', '  function startLive(');
const token=sub=>({accessToken:'x.'+Buffer.from(JSON.stringify({sub})).toString('base64url')+'.x'});
function fixture(store=new Map(),owner='one'){
 const c=vm.createContext({atob,session:token(owner),liveAuthEpoch:1,liveError:null,localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v),removeItem:k=>store.delete(k)},esc:s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;'),money:n=>n+'원',num:String,kstStamp:String});vm.runInContext(code,c);
 const target={authOwner:1,accounts:[{id:'a'}],snapshots:[{snapshot_at:'2026-10-09T12:00:00Z',total_assets:10000}],accountScope:{ok:true,current_display_total:12000},securityMap:{s:{name:'테스트 종목',symbol:'TEST'}},holdings:[{account_id:'a',security_id:'s',quantity:2}],holdingBasis:[{account_id:'a',security_id:'s',valuation_krw:8000}]};
 return {c,target,store};
}
test('fresh runtime restores a small display snapshot, never auth or transaction state',()=>{const f=fixture();f.c.rememberHomeSnapshot(f.target);const n=fixture(f.store);const p=n.c.readHomeSnapshot();assert.equal(p.data.total,12000);assert.equal(p.data.rows[0].value,8000);assert.equal(p.data.rows[0].quantity,2);assert.doesNotMatch([...f.store.values()][0],/accessToken|transactions|price_snapshot/);assert.match(n.c.homeSnapshotHtml(p),/마지막 확인 총자산/);assert.match(n.c.homeSnapshotHtml(p),/최신 계좌 확인 중/)});
test('snapshot is isolated by authenticated subject and logout removes it',()=>{const f=fixture();f.c.rememberHomeSnapshot(f.target);assert.equal(fixture(f.store,'other').c.readHomeSnapshot(),null);f.c.clearHomeSnapshot();assert.equal(fixture(f.store).c.readHomeSnapshot(),null)});
test('old owner late response cannot write into current owner cache',()=>{const f=fixture();f.c.liveAuthEpoch=2;f.c.rememberHomeSnapshot(f.target);assert.equal(f.store.size,0)});
test('missing valuation remains unknown, never zero; account total uses defined fallback',()=>{const f=fixture();f.target.holdingBasis=[];f.target.accountScope=null;f.c.rememberHomeSnapshot(f.target);const p=f.c.readHomeSnapshot();assert.equal(p.data.total,10000);assert.equal(p.data.rows[0].value,null);assert.match(f.c.homeSnapshotHtml(p),/평가액 확인 필요/)});
test('multiple accounts aggregate only fully-known valuations',()=>{const f=fixture();f.target.holdings.push({account_id:'b',security_id:'s',quantity:3});f.c.rememberHomeSnapshot(f.target);assert.equal(f.c.readHomeSnapshot().data.rows[0].value,null);f.target.holdingBasis.push({account_id:'b',security_id:'s',valuation_krw:9000});f.c.rememberHomeSnapshot(f.target);assert.equal(f.c.readHomeSnapshot().data.rows[0].value,17000)});
test('expired, future, malformed, oversized and invalid numeric caches are ignored',()=>{const f=fixture();f.c.rememberHomeSnapshot(f.target);const k=f.c.homeSnapshotKey(),original=JSON.parse(f.store.get(k));for(const change of [{savedAt:new Date(Date.now()-8*86400000).toISOString()},{savedAt:new Date(Date.now()+86400000).toISOString()},{total:null},{rows:[{name:'bad',symbol:'X',quantity:'2',value:0}]},{version:2}]){f.store.set(k,JSON.stringify({...original,...change}));assert.equal(f.c.readHomeSnapshot(),null)}f.store.set(k,'{broken');assert.equal(f.c.readHomeSnapshot(),null);f.store.set(k,' '.repeat(250001));assert.equal(f.c.readHomeSnapshot(),null)});
test('local storage failure never breaks the online flow',()=>{const f=fixture();f.c.localStorage.setItem=()=>{throw Error('quota')};assert.doesNotThrow(()=>f.c.rememberHomeSnapshot(f.target));assert.equal(f.c.readHomeSnapshot(),null);f.c.localStorage.getItem=()=>{throw Error('blocked')};assert.equal(f.c.readHomeSnapshot(),null)});
test('offline preview offers retry with saved timestamp and escaped labels',()=>{const f=fixture();f.target.securityMap.s.name='<img src=x>';f.c.rememberHomeSnapshot(f.target);f.c.liveError='offline';const p=f.c.readHomeSnapshot(),out=f.c.homeSnapshotHtml(p);assert.match(out,/data-home-load-retry/);assert.match(out,/저장된 요약/);assert.ok(out.includes(p.data.savedAt));assert.doesNotMatch(out,/<img/);assert.doesNotMatch(out,/data-security-id|data-decision/)});
test('confirmed empty account clears previous preview; successful current load updates amount',()=>{const f=fixture();f.c.rememberHomeSnapshot(f.target);f.target.accountScope.current_display_total=15000;f.c.rememberHomeSnapshot(f.target);assert.equal(f.c.readHomeSnapshot().data.total,15000);f.target.accounts=[];f.c.rememberHomeSnapshot(f.target);assert.equal(f.c.readHomeSnapshot(),null)});
