import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const s=fs.readFileSync('index.html','utf8');
const c=vm.createContext({esc:String,signedMoney:n=>Math.round(n).toLocaleString('en-US')+'원',cls:n=>n<0?'down':'up'});
vm.runInContext(s.slice(s.indexOf('  function sortedStockPnl('),s.indexOf('  function stockPeriodLabel(')),c);
const known={symbol:'KR',currency:'KRW',pnl_krw:10000};
const foreign={symbol:'FX',currency:'USD',pnl_local:-20,pnl_krw:null,local_cash_only:true,reference_pnl_krw:-30000,separate_cash_krw:-2000,reference_fx_basis:'event_date_with_ledger_fallback',reference_ledger_date_count:3};
const p={period:'ALL',items:[known,foreign],provisional_count:1};
assert.equal(c.stockReferenceOverview(p).total,-22000);
assert.equal(c.stockReferenceOverview(p).ledgerDates,3);
assert.equal(c.stockReferenceOverview({...p,period:'1M'}),null);
for(const bad of [null,'','NaN',Infinity])assert.equal(c.stockReferenceOverview({...p,items:[known,{...foreign,reference_pnl_krw:bad}]}),null);
assert.equal(c.stockReferenceOverview({...p,items:[known,{...foreign,reference_fx_basis:'spot'}]}),null);
assert.equal(c.stockReferenceOverview({...p,items:[known,{symbol:'UNKNOWN'}]}),null);
assert.equal(c.stockReferenceOverview({...p,items:[known]}),null);
const h=c.stockReferenceHtml(p);
assert.match(h,/<details/);assert.match(h,/-22,000원/);assert.match(h,/체결일 미확인 3건/);assert.match(h,/잠정/);
assert.equal(foreign.pnl_krw,null);assert.equal(foreign.pnl_local,-20);
assert.equal(c.stockPnlOverview(p).krwWithTax,8000);
console.log('Build128: reference-only full coverage, separate tax once, invalid/missing amounts rejected, verified totals unchanged');
