import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
const html=fs.readFileSync('index.html','utf8'),storage=new Map();let renders=0;
const c=vm.createContext({sget:k=>storage.get(k),sset:(k,v)=>storage.set(k,v),render:()=>renders++});
vm.runInContext(html.slice(html.indexOf('  function reduceSwingAlerts('),html.indexOf('  function homePriceWatchData(')),c);
const point=(date='2026-10-06',drawdown=-15,peak='2026-09-25',id='a',currency='USD')=>({id,name:id,date,drawdown,currency,peak:{date:peak,close:100}});
const step=(state,obs,held=['a'])=>c.reduceSwingAlerts(state,obs,held);
let r=step({},[point()]);assert.equal(r.events.length,1,'exact threshold alerts');assert.equal(r.state.a.unread,true);
r=step(r.state,[point()]);assert.equal(r.events.length,0,'repeat read dedup');r=step(r.state,[point('2026-10-07',-20)]);assert.equal(r.events.length,0,'continued fall dedup');
r=step(r.state,[]);assert.equal(r.state.a.active,true,'missing or stale quote does not rearm');
r=step(r.state,[point('2026-10-06',-10)]);assert.equal(r.state.a.active,true,'old response cannot rearm');
r=step(r.state,[point('2026-10-08',-14)]);assert.equal(r.state.a.active,false);
r=step(r.state,[point('2026-10-09',-15)]);assert.equal(r.events.length,1,'recovered and reentered');
r=step(r.state,[point('2026-10-10',-15,'2026-10-01')]);assert.equal(r.events.length,1,'new confirmed peak');
assert.equal(step(r.state,[],[]).state.a,undefined,'sold security pruned');
assert.equal(step({a:{broken:true}},[point()]).events.length,1,'malformed stored entry recovers');
assert.equal(step({},[point('2026-10-06',-14.99)]).events.length,0);
assert.equal(step({},[point(),point('2026-10-06',-18,'2026-09-25','b','KRW')],['a','b']).events.length,2,'KRW and USD');
const first={accounts:[{id:'account-one'}],holdings:[{security_id:'a',quantity:1}]};c.live=first;c.homePriceWatchData=()=>({observations:[point()]});c.updateSwingAlerts(first);assert.equal(first.swingAlertState.a.unread,true);
c.acknowledgeSwingAlerts();assert.equal(first.swingAlertState.a.unread,false);assert.equal(renders,1);
const reload={accounts:first.accounts,holdings:first.holdings};c.live=reload;c.updateSwingAlerts(reload);assert.equal(reload.swingAlertState.a.unread,false,'ack survives reload');
const other={accounts:[{id:'account-two'}],holdings:first.holdings};c.live=other;c.updateSwingAlerts(other);assert.equal(other.swingAlertState.a.unread,true,'accounts isolated');
c.updateSwingAlerts(reload);assert.equal(reload.swingAlertState.a.unread,false,'old snapshot ignored');
assert.match(html,/앱이 닫힌 동안 자동 푸시는 제공되지 않습니다/);
console.log('Build147: threshold, continued fall, recovery, new peak, missing/stale data, KRW/USD, persistent acknowledgment and account isolation passed');
