import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {stripTypeScriptTypes} from 'node:module';
const worker=fs.readFileSync(new URL('../supabase/functions/kb-sync-worker/index.ts',import.meta.url),'utf8');
const c=vm.createContext({});
vm.runInContext(stripTypeScriptTypes(worker.slice(worker.indexOf('function attachNativePrices('),worker.indexOf('async function syncCurrent('))),c);
const raw={is_cd:'TEST',mkt_clsf:'NAS',crncy_clsf_nm:'USD',now_prc_p4:'130000',std_exch_r:'1300'};
const h={symbol:'TEST',currency:'USD',quantity:4,avg_cost:150000,market_price:130000,market_value:400,unrealized_pnl:-60,provider_payload:raw};
const row={...raw,frgn_hld_q_p6:'4.000000',byng_avr_prc_p4:'115.0000',now_prc_p4:'100.0000',byng_amt:'460.00'};
const stamp='2026-09-30T10:00:00Z';
const attach=(rows,hs=[h])=>c.attachNativePrices(hs,{dataBody:{Record2:rows}},stamp);
const result=attach([row])[0];
assert.equal(result.provider_payload.native_prices.average_price,115);
assert.equal(result.provider_payload.native_prices.market_price,100);
for(const k of Object.keys(h).filter(k=>k!=='provider_payload'))assert.deepEqual(result[k],h[k]);
assert.deepEqual(h.provider_payload,raw);assert.equal(raw.native_prices,undefined);
for(const rows of [[],[row,row],[{...row,is_cd:'OTHER'}],[{...row,mkt_clsf:'NYS'}],[{...row,crncy_clsf_nm:'JPY'}],[{...row,frgn_hld_q_p6:'3'}],[{...row,byng_amt:'400'}],[{...row,now_prc_p4:'130000'}]])assert.equal(attach(rows)[0],h);
for(const field of ['frgn_hld_q_p6','byng_avr_prc_p4','now_prc_p4','byng_amt'])for(const value of [null,undefined,'',0,-1,'invalid',Infinity])assert.equal(attach([{...row,[field]:value}])[0],h);
assert.equal(attach([row],[h,h])[0],h);
assert.equal(c.attachNativePrices([h],null,stamp)[0],h);
// Same symbol in a distinct market cannot donate its prices.
assert.equal(attach([{...row,mkt_clsf:'NYS',byng_avr_prc_p4:120},row])[0].provider_payload.native_prices.average_price,115);
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
const ui=vm.createContext({esc:String,price:(v,u)=>`${v.toFixed(2)} ${u}`,money:v=>`${v}원`,kstStamp:String});
vm.runInContext(html.slice(html.indexOf('  function holdingPriceSummaryHtml('),html.indexOf('  function decisionReviewHtml(')),ui);
const pos={...h,as_of:'2026-09-30T10:00:01Z',native_prices:result.provider_payload.native_prices};
const render=p=>ui.holdingPriceSummaryHtml([p],[],[],'USD');
assert.match(render(pos),/평균 매입가<\/span><strong>115.00 USD/);
assert.match(render(pos),/잔고 조회 가격<\/span><strong>100.00 USD/);
assert.doesNotMatch(render(pos),/환산 평균|150000 USD|130000 USD/);
for(const patch of [{source:'other'},{currency:'KRW'},{quantity:3},{observed_at:'invalid'},{observed_at:'2026-09-29T00:00:00Z'},{observed_at:'2026-09-30T10:01:00Z'},{average_price:0},{market_price:null}])assert.match(render({...pos,native_prices:{...pos.native_prices,...patch}}),/환산 평균 매입가<\/span><strong>확인 중/);
console.log('Build104: native price identity, scale, quantity, freshness, fallback and unchanged accounting passed');
