import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
const source=readFileSync(new URL('../index.html',import.meta.url),'utf8');
const fn=source.slice(source.indexOf('  function changeStockPeriod('),source.indexOf('  function stockPeriodPerformance('));
const requests=[];
const ctx={stockPeriod:'THIS_MONTH',stockPeriodEpoch:0,live:{stockPnl:{ok:true,period:'THIS_MONTH'}},render(){},rpc:(_,p)=>new Promise((resolve,reject)=>requests.push({p,resolve,reject}))};
vm.createContext(ctx);vm.runInContext(fn,ctx);
ctx.changeStockPeriod('1W');ctx.changeStockPeriod('1M');
requests[1].resolve({ok:true,period:'1M',pnl_krw:12});await new Promise(setImmediate);
requests[0].resolve({ok:true,period:'1W',pnl_krw:99});await new Promise(setImmediate);
assert.equal(ctx.live.stockPnl.pnl_krw,12);
ctx.changeStockPeriod('YTD');requests[2].reject(Error('offline'));await new Promise(setImmediate);
assert.equal(ctx.live.stockPnl,null);assert.equal(ctx.live.stockPnlFailed,true);
ctx.changeStockPeriod('YTD');requests[3].resolve({ok:true,period:'YTD'});await new Promise(setImmediate);
assert.equal(ctx.live.stockPnlFailed,false);
ctx.changeStockPeriod('1W');const replacement={stockPnl:null};ctx.live=replacement;
requests[4].resolve({ok:true,period:'1W'});await new Promise(setImmediate);
assert.equal(ctx.live.stockPnl,null);
console.log('Period P&L: late response, failed fetch, retry and replaced account data passed');
